### ISSUE TITLE
error loading module requirements 

### ISSUE THREAD

**Issue by bilo1967** [notedit/rtclive#11]
After installing prerequisites, I tried tp `cd ~/media-server-go-native/rtclive` and run a `go build` 
I got an error:
```
go: parsing ../../media-server-go/go.mod: open /home/me/media-server-go/go.mod: no such file or directory
```
I copied  the `go/src/github.com/notedit/media-server-go` from its location to  `~/media-server-go` and tried again a `go build` .

Now I get 
```
# pkg-config --cflags  -- gstreamer-1.0 gstreamer-base-1.0 gstreamer-app-1.0 gstreamer-plugins-base-1.0 gstreamer-video-1.0 gstreamer-audio-1.0 gstreamer-plugins-bad-1.0
Package gstreamer-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-1.0.pc'
to the PKG_CONFIG_PATH environment variable
...
```
and then more similar errors.
What am I doing wrong?

**Comment by notedit** [comment]
you did not install the gstreamer.  

you can find https://github.com/notedit/rtclive/blob/master/.travis.yml
