### ISSUE TITLE
网页无法播放rtmp->webrtc 视频

### ISSUE THREAD

**Issue by xfzen** [notedit/rtclive#7]
rtclive默认使用的是media-server-go v0.1.6版本，经过测试有些问题：

1. webrtc push，webrtc play正常
2. rtmp push(obs/ffmpeg)，webrtc play异常，没有视频

经过反复测试与验证，与media-server-go版本有关系；使用media-servefr-go v0.1.5版本，#2中 rtmp推流，webrtc 播放是正常的

另，请问media-server或media-server-go的日志该如何查看，或者说日志是否可以配置写入日志文件的？没有日志，出现异常的时候很难确定是什么原因（如缺乏gst的插件，或别的原因）

谢谢

**Comment by notedit** [comment]
有可能是gstreamer的插件没装好,   gstreamer good,  gstreamer bad,  gstreamer ugly 需要安装 

我增加了一些gstreamer-go的安装文档  https://github.com/notedit/gstreamer-go,  可以先检查一下这里.

另外rtmp push的时候  确保264 编码是baseline  否则可能会出现适配问题

**Comment by notedit** [comment]
可以看一下这个能不能解决你的问题   https://github.com/notedit/rtclive/issues/5

**Comment by xfzen** [comment]
1. 确认不是gsteramer插件问题
经过初步测试与media-server-go版本有关系
a）v0.1.6/v0.1.7版本均是有问题
b）v0.1.5版本是正常的

2. 请问要怎么开启media-server/media-server-go/gst 的日志？

**Comment by notedit** [comment]
export  GST_DEBUG=2

**Comment by notedit** [comment]
版本问题 我周末验证一下

**Comment by notedit** [comment]
是有问题,  打算重构一下这里

**Comment by notedit** [comment]
done
